import reflex as rx
from python_links.components.link_button import link_button
from python_links.components.title import title
import python_links.constants as const

def links() -> rx.Component:
    return rx.vstack(
        title("Comunidad"),
        link_button("Twitch", 
                    "Directos de Lunes a viernes",
                    "/icons/twitch.svg",
                    "https://twitch.com",
                    ),
        link_button("Youtube", 
                    "Videos Semanales",
                    "/icons/youtube.svg",
                    "https://twitch.com"),
        link_button("Github",
                    "Mi perfil de Github",
                    "/icons/github.svg",
                    "https://twitch.com"),
        link_button("Discord",
                    "El chat de la comunidad",
                    "/icons/discord.svg",
                    "https://twitch.com"),
        title("Comunidad"),
        link_button("Twitch", 
                    "Directos de Lunes a viernes",
                    "/icons/twitch.svg",
                    "https://twitch.com",
                    ),
        link_button("Youtube", 
                    "Videos Semanales",
                    "/icons/twitch.svg",
                    "https://twitch.com"),
        link_button("Github",
                    "Mi perfil de Github",
                    "/icons/twitch.svg",
                    "https://twitch.com"),
        link_button("Discord",
                    "El chat de la comunidad",
                    "/icons/twitch.svg",
                    "https://twitch.com"),
        title("Contacto"),
        link_button("Twitch", 
                    "Directos de Lunes a viernes",
                    "/icons/twitch.svg",
                    "https://twitch.com",
                    ),
        link_button("Youtube", 
                    "Videos Semanales",
                    "/icons/twitch.svg",
                    "https://twitch.com"),
        width="100%",
        spacing="2"
    )